# S3
AWS_ACCESS_KEY_ID = 'ACCESS KEY DE AWS'
AWS_SECRET_ACCESS_KEY = 'SECRET ACCESS KEY DE AWS'
S3_BUCKET_NAME = 'BUCKET NAME'
S3_IAM_ROLE = 'DEFINITION OF THE IAM ROLE'
S3_DELIMITER = 'DEFAULT FIELD DELIMITER'

# REDSHIFT DATABASE
host = 'ADRESS OF THE DATABASE'
port = 'PORT OF THE DATABASE'
dbname = 'NAME OF THE DATABASE'
user = 'USER TO ACCESS THE DATABASE'
password = 'PASSWORD TO ACCESS THE DATABASE'

# SLACK
SLACK_CHANNEL_LOGS = 'URL OF THE HOOK SERVICE'

# HUBSPOT
HUBSPOT_API_KEY = "HUBSPOT API KEY"
HUBSPOT_URL_BASE_CAMPAIGN = 'https://api.hubapi.com/email/public/v1/campaigns/'
HUBSPOT_URL_BASE_EVENTS = 'https://api.hubapi.com/email/public/v1/events'
HUBSPOT_URL_BASE_MKT_EMAILS = 'https://api.hubapi.com/marketing-emails/v1/emails'

# AIRCALL
AIRCALL_API_ID = 'ID OF THE AIRCALL API'
AIRCALL_API_TOKEN = 'TOKEN OF THE AIRCALL API'
AIRCALL_ROWS_PER_PAGE = 50

# FOUNTAIN
FOUNTAIN_FIEDS = [
    'FIELDS THAT ARE GOING TO BE USED FROM FOUNTAIN'
]
FOUNTAIN_TOKEN = 'TOKEN TO ACCESS TO FOUNTAIN'
FOUNTAIN_TEMPLATE_ID = 'ID OF THE FOUNTAIN TEMPLATE'
FOUNTAIN_URL_BASE = 'https://api.fountain.com/v2/timestamped_exports'


# DELIGHTED
DELIGHTED_API_KEY_CSAT = 'KEY TO ACCESS CSAT DATA IN DELIGHTED'
DELIGHTED_API_KEY_NPS = 'KEY TO ACCESS NPS DATA IN DELIGHTED'
DELIGHTED_API_KEY_CSAT_V2 = 'KEY TO ACCESS THE SECOND VERSION OF CSAT DATA IN DELIGHTED'

# HELPSCOUT
HELPSCOUT_API_KEY = 'KEY TO ACCESS TO THE HELPSCOUT APU'
HELPSCOUT_API_ID = 'ID TO ACCESS TO THE HELPSCOUT APU'
HELPSCOUT_APP_SECRET = 'APP SECRET TO ACCESS TO THE HELPSCOUT APU'
